token = '6619270966:AAEy_zJ_GbUy1ikfahj22CUE4yYAoUEUsuc'
youtube_video = 'https://www.youtube.com/watch?v=GV3Vb0cUsQY&list=PLBnDGoKqP7bbXfM7jrSQzkTEkFJdF4YxP'
youtube_inf1 = 'https://www.youtube.com/playlist?list=PLvtJKssE5Nrid_m5JTWqfAJuIDI4bNG_C'
youtube_inf2 = 'https://www.youtube.com/watch?v=py20yTnkme4&list=PLudSw-n_9sI7E8bn6S1TBc1Bbg3U21uDK'
youtube_inf3 = 'https://www.youtube.com/watch?v=A5chdV6tsSk&list=PLudSw-n_9sI58Gb9emvANIqM1RHIKocjr'